-- H2 与 OrderMapper.xml 中 orders 表字段对齐（测试用）
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(64),
    status INT,
    user_id BIGINT,
    address_book_id BIGINT,
    order_time TIMESTAMP,
    checkout_time TIMESTAMP,
    pay_method INT,
    pay_status INT,
    amount DECIMAL(10, 2),
    remark VARCHAR(255),
    phone VARCHAR(32),
    address VARCHAR(255),
    user_name VARCHAR(64),
    consignee VARCHAR(64),
    cancel_reason VARCHAR(255),
    rejection_reason VARCHAR(255),
    cancel_time TIMESTAMP,
    estimated_delivery_time TIMESTAMP,
    delivery_status INT,
    delivery_time TIMESTAMP,
    pack_amount INT DEFAULT 0,
    tableware_number INT DEFAULT 0,
    tableware_status INT
);
